name: libbpf-bootstrap build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_libbpf_bootstrap:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        llvm: [18]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build container (22.04)
      if: ${{ matrix.llvm >= 14 }}
      uses: docker/build-push-action@v3
      with:
        push: false
        build-args: |
          LLVM_VERSION=${{ matrix.llvm }}
          VERSION=22.04
          SHORTNAME=jammy
        file: ./.github/docker/Dockerfile.ubuntu
        tags: build_container
    - name: Build xmake android examples/c
      run: |
        docker run \
          -v $(pwd):/libbpf-bootstrap \
          build_container \
          /bin/bash -c \
          'curl -fsSL https://xmake.io/shget.text | bash'
        docker run \
          -v $(pwd):/libbpf-bootstrap \
          build_container \
          /bin/bash -c \
          'source ~/.profile && source ~/.bashrc'
        docker run \
          -v $(pwd):/libbpf-bootstrap \
          build_container \
          /bin/bash -c \
          'cd /libbpf-bootstrap/examples/c && xmake f -p android --root && xmake --root'
