name: libbpf-bootstrap android ubuntu

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_libbpf_bootstrap_android:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: 'latest'
    - name: Install Dependencies
      run: |
        apt-get install DEBIAN_FRONTEND="noninteractive" -y \
          libelf-dev \
          zlib1g-dev \
          libbfd-dev \
          clang \
          libclang-dev \
          libclang-common-dev \
          libclang1 \
          llvm \
          llvm-dev \
          llvm-runtime \
          libllvm\
          make pkg-config \
          rustc cargo rustfmt \
          sudo \
          && apt-get -y clean
    - name: Build xmake android examples/c
      run: |
        cd /libbpf-bootstrap/examples/c && xmake f -p android && xmake
